baseURL = 'https://edu-transformer.github.io/'
languageCode = 'en-us'
title = 'Edu Transformer'
publishDir = "docs"
enableRobotsTXT = true

defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "EN"
    languageCode = "en-us"
    weight = 1
    contentDir = 'content/en'
  [languages.pl]
    title = "PL"
    languageCode = "pl-pl"
    weight = 2
    contentDir = 'content/pl'

